  # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
 #     다음과 같은 구조를 가지고 있다는 가정 하에 동작합니다.    # 
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#  MidProject/                                            #
#  ├─ .env.development                                    #
#  ├─ .env.test                                           #
#  ├─ .env.production                                     #
#  ├─ docker-compose.yml                                  #
#  │                                                      #
#  ├─ backend/                                            #  
#  │  └─ Dockerfile                                       #  
#  │                                                      #      
#  └─ routing-worker/                                     #    
#     └─ Dockerfile                                       #    
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
services:
  backend: # Node 서버
    build: # `./backend/Dockerfile` 을 빌드합니다.
      context: ./backend 
    env_file:
      - .env.development
    ports:
      - "3000:3000"
    depends_on: # DB와 워커 FastAPI가 먼저 시작 후 실행 (healthcheck를 이용해서 서버 정상동작까지 가능)
      - database
      - routing-worker
  
  routing-worker:
    build: # `/routing-worker/Dockerfile` 을 빌드합니다.
      context: ./routing-worker
    env_file: # 메인 폴더의 환경을 그대로 사용합니다.
      - .env.development
    
    # ports는 fastapi 워커 테스트 시에만 사용
    ports: # FastAPI의 기본 포트인 8000번을 호스트의 포트와 연결시킵니다.
      - "8000:8000"
    
  database:
    # PostGIS Extention이 붙어있는 17-3.5 버전을 거져옵니다.
    image: postgis/postgis:17-3.5
    env_file: # 동일한 파일에서 환경변수를 관리해줍니다.
      - .env.development
    ports:
      - "5432:5432"
    volumes: # 컨테이너 데비안의 /var/lib/postgrersql/data에 있는 데이터를 볼륨으로 영속화합니다.
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: