import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F7F8FA',
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 40,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 26,
  },
  logoMark: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    backgroundColor: '#04045E',
  },
  logoLetter: {
    color: '#B9FA3C',
    fontSize: 18,
    fontWeight: '800',
  },
  brandName: {
    color: '#04045E',
    fontSize: 20,
    fontWeight: '800',
  },
  heading: {
    color: '#04045E',
    fontSize: 26,
    fontWeight: '800',
  },
  subheading: {
    color: '#6F7B80',
    fontSize: 15,
    marginTop: 7,
    marginBottom: 20,
  },
  heroCard: {
    backgroundColor: '#F8F9FF',
    borderWidth: 1,
    borderColor: '#DDE2F5',
    borderRadius: 28,
    padding: 24,
  },
  heroCopy: {
    flex: 1,
    zIndex: 1,
  },
  heroEyebrow: {
    color: '#100078',
    fontSize: 26,
    fontWeight: '900',
    fontStyle: 'italic',
    letterSpacing: -1.5,
    lineHeight: 35,
  },
  heroTitle: {
    color: '#172E38',
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 29,
    marginTop: 9,
  },
  primaryButton: {
    alignSelf: 'flex-start',
    justifyContent: 'center',
    minHeight: 42,
    borderRadius: 12,
    backgroundColor: '#172E38',
    paddingHorizontal: 19,
    marginTop: 20,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  courseIllustration: {
    width: '82%',
    height: 160,
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 14,
  },

  heroFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  heroMessage: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  heroDescription: {
    color: '#100078',
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
  },
  courseButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minHeight: 46,
    borderRadius: 23,
    backgroundColor: '#B7FF28',
    paddingLeft: 16,
    paddingRight: 6,
    flexShrink: 0,
    overflow: 'hidden',
  },
  courseButtonText: {
    color: '#100078',
    fontSize: 15,
    fontWeight: '800',
  },
  courseButtonArrow: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#100078',
  },
  arrowShaft: {
    position: 'absolute',
    left: 9,
    width: 15,
    height: 2.5,
    borderRadius: 99,
    backgroundColor: '#FFFFFF',
  },
  arrowHead: {
    position: 'absolute',
    right: 8,
    width: 10,
    height: 2.5,
    borderRadius: 99,
    backgroundColor: '#FFFFFF',
  },
  arrowHeadTop: {
    top: 12,
    transform: [{ rotate: '45deg' }],
  },
  arrowHeadBottom: {
    bottom: 12,
    transform: [{ rotate: '-45deg' }],
  },
  summaryRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  summaryCard: {
    flex: 1,
    minHeight: 78,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E6EAEC',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
  },
  summaryLabel: {
    color: '#778287',
    fontSize: 12,
  },
  summaryValue: {
    color: '#172E38',
    fontSize: 19,
    fontWeight: '800',
    marginTop: 6,
  },
  summaryHelp: {
    color: '#8A9499',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 9,
  },
  errorCard: {
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#F2C8C8',
    borderRadius: 14,
    backgroundColor: '#FFF8F8',
    padding: 16,
    marginTop: 14,
  },
  errorText: { color: '#D84A4A', fontSize: 12, textAlign: 'center' },
  retryText: { color: '#100078', fontSize: 12, fontWeight: '800', marginTop: 8 },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 30,
    marginBottom: 12,
  },
  sectionTitle: {
    color: '#172E38',
    fontSize: 19,
    fontWeight: '800',
  },
  moreText: {
    color: '#68757A',
    fontSize: 13,
    fontWeight: '600',
  },
  emptyCard: {
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E6EAEC',
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingVertical: 25,
  },
  dataCard: {
    borderWidth: 1,
    borderColor: '#E6EAEC',
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    padding: 18,
  },
  dataTitle: { color: '#172E38', fontSize: 16, fontWeight: '800' },
  dataMeta: { color: '#7A858A', fontSize: 12, lineHeight: 18, marginTop: 7 },
  goalTrack: {
    height: 8,
    overflow: 'hidden',
    borderRadius: 4,
    backgroundColor: '#E7E9EF',
    marginTop: 15,
  },
  goalFill: { height: '100%', borderRadius: 4, backgroundColor: '#A7EF2A' },
  emptyIcon: {
    width: 42,
    height: 42,
    borderWidth: 9,
    borderColor: '#DFF7E8',
    borderRadius: 21,
    backgroundColor: '#7BE0A4',
    marginBottom: 13,
  },
  emptyTitle: {
    color: '#26383F',
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
  },
  emptyDescription: {
    color: '#7A858A',
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
    marginTop: 6,
  },
  secondaryButton: {
    justifyContent: 'center',
    minHeight: 40,
    borderRadius: 11,
    backgroundColor: '#E8F8EE',
    paddingHorizontal: 17,
    marginTop: 16,
  },
  secondaryButtonText: {
    color: '#218653',
    fontSize: 13,
    fontWeight: '700',
  },
  buttonPressed: {
    opacity: 0.72,
  },
});
