import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F7F8FA',
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 40,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 26,
  },
  logoMark: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    backgroundColor: '#172E38',
  },
  logoLetter: {
    color: '#7BE0A4',
    fontSize: 18,
    fontWeight: '800',
  },
  brandName: {
    color: '#172E38',
    fontSize: 20,
    fontWeight: '800',
  },
  heading: {
    color: '#172E38',
    fontSize: 26,
    fontWeight: '800',
  },
  subheading: {
    color: '#6F7B80',
    fontSize: 15,
    marginTop: 7,
    marginBottom: 20,
  },
  heroCard: {
    minHeight: 210,
    flexDirection: 'row',
    overflow: 'hidden',
    borderRadius: 20,
    backgroundColor: '#DFF7E8',
    padding: 20,
  },
  heroCopy: {
    flex: 1,
    zIndex: 1,
  },
  heroEyebrow: {
    color: '#218653',
    fontSize: 13,
    fontWeight: '700',
  },
  heroTitle: {
    color: '#172E38',
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 29,
    marginTop: 9,
  },
  primaryButton: {
    alignSelf: 'flex-start',
    justifyContent: 'center',
    minHeight: 42,
    borderRadius: 12,
    backgroundColor: '#172E38',
    paddingHorizontal: 19,
    marginTop: 20,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  courseIllustration: {
    position: 'absolute',
    right: -8,
    bottom: -6,
    width: 155,
    height: 145,
    borderRadius: 72,
    backgroundColor: '#BDEECB',
  },
  routeLineOne: {
    position: 'absolute',
    left: 22,
    top: 52,
    width: 104,
    height: 9,
    borderRadius: 5,
    backgroundColor: '#FFFFFF',
    transform: [{ rotate: '-22deg' }],
  },
  routeLineTwo: {
    position: 'absolute',
    left: 44,
    top: 82,
    width: 86,
    height: 9,
    borderRadius: 5,
    backgroundColor: '#FFFFFF',
    transform: [{ rotate: '38deg' }],
  },
  routeStart: {
    position: 'absolute',
    left: 18,
    top: 64,
    width: 17,
    height: 17,
    borderWidth: 4,
    borderColor: '#218653',
    borderRadius: 9,
    backgroundColor: '#FFFFFF',
  },
  routeFinish: {
    position: 'absolute',
    right: 19,
    bottom: 27,
    width: 18,
    height: 18,
    borderWidth: 4,
    borderColor: '#172E38',
    borderRadius: 9,
    backgroundColor: '#FFFFFF',
  },
  summaryRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  summaryCard: {
    flex: 1,
    minHeight: 78,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E6EAEC',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
  },
  summaryLabel: {
    color: '#778287',
    fontSize: 12,
  },
  summaryValue: {
    color: '#172E38',
    fontSize: 19,
    fontWeight: '800',
    marginTop: 6,
  },
  summaryHelp: {
    color: '#8A9499',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 9,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 30,
    marginBottom: 12,
  },
  sectionTitle: {
    color: '#172E38',
    fontSize: 19,
    fontWeight: '800',
  },
  moreText: {
    color: '#68757A',
    fontSize: 13,
    fontWeight: '600',
  },
  emptyCard: {
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E6EAEC',
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingVertical: 25,
  },
  emptyIcon: {
    width: 42,
    height: 42,
    borderWidth: 9,
    borderColor: '#DFF7E8',
    borderRadius: 21,
    backgroundColor: '#7BE0A4',
    marginBottom: 13,
  },
  emptyTitle: {
    color: '#26383F',
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
  },
  emptyDescription: {
    color: '#7A858A',
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
    marginTop: 6,
  },
  secondaryButton: {
    justifyContent: 'center',
    minHeight: 40,
    borderRadius: 11,
    backgroundColor: '#E8F8EE',
    paddingHorizontal: 17,
    marginTop: 16,
  },
  secondaryButtonText: {
    color: '#218653',
    fontSize: 13,
    fontWeight: '700',
  },
  buttonPressed: {
    opacity: 0.72,
  },
});
