import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F7F8FA' },
  header: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
  },
  backButton: { width: 36, color: '#0A145A', fontSize: 38, lineHeight: 40 },
  screenTitle: { color: '#0A145A', fontSize: 22, fontWeight: '900' },
  content: { padding: 20, paddingBottom: 44 },
  recordDate: { color: '#7D8495', fontSize: 14 },
  summaryCard: {
    flexDirection: 'row',
    borderRadius: 18,
    backgroundColor: '#100078',
    paddingVertical: 24,
    marginTop: 14,
  },
  metricItem: { flex: 1, alignItems: 'center' },
  metricValue: { color: '#C8FF30', fontSize: 17, fontWeight: '900' },
  metricLabel: { color: '#C4C6DA', fontSize: 11, marginTop: 6 },
  sectionTitle: { color: '#0A145A', fontSize: 19, fontWeight: '900', marginTop: 30, marginBottom: 14 },
  segmentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#E7E9EF',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  segmentLabel: { color: '#7D8495', fontSize: 13 },
  segmentValue: { color: '#17204E', fontSize: 15, fontWeight: '800' },
  messageCard: {
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E0E3EB',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    padding: 24,
  },
  messageText: { color: '#7D8495', fontSize: 13, textAlign: 'center' },
  errorText: { color: '#E5484D', fontSize: 13, textAlign: 'center' },
  retryText: { color: '#100078', fontSize: 13, fontWeight: '800', marginTop: 14 },
  mapNotice: { color: '#9299A8', fontSize: 12, lineHeight: 18, marginTop: 24, textAlign: 'center' },
});
