import { StyleSheet } from 'react-native';

import { colors } from '@/styles/tokens';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.white },
  content: { paddingBottom: 52 },
  header: {
    alignItems: 'center',
    borderBottomColor: '#F3F4F6',
    borderBottomWidth: 1,
    flexDirection: 'row',
    minHeight: 96,
    paddingHorizontal: 28,
  },
  backButton: { color: colors.navy, fontSize: 40, lineHeight: 42, width: 38 },
  screenTitle: { color: colors.navy, fontSize: 22, fontWeight: '900', marginLeft: 10 },
  screenDescription: { color: '#7A8292', fontSize: 14, marginTop: 7 },
  filterRow: {
    flexDirection: 'row',
    borderRadius: 16,
    backgroundColor: colors.inactive,
    marginHorizontal: 28,
    padding: 4,
    marginTop: 24,
  },
  filterButton: {
    flex: 1,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
  },
  filterButtonActive: { backgroundColor: colors.white },
  filterText: { color: colors.muted, fontSize: 13, fontWeight: '700' },
  filterTextActive: { color: colors.navy },
  summaryCard: {
    minHeight: 136,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.pageIndigo,
    paddingHorizontal: 23,
    paddingVertical: 18,
    marginTop: 17,
  },
  summaryMetric: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 20,
    elevation: 2,
    flex: 1,
    marginHorizontal: 5,
    minHeight: 100,
    justifyContent: 'center',
    shadowColor: '#0B0E35',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 5,
  },
  summaryLabel: { color: colors.muted, fontSize: 12, marginTop: 8 },
  summaryValueRow: { flexDirection: 'row', alignItems: 'flex-end', marginTop: 8 },
  summaryValue: { color: colors.navy, fontSize: 23, fontWeight: '900' },
  summaryUnit: { color: colors.navy, fontSize: 11, marginLeft: 2, marginBottom: 3 },
  summaryDivider: { width: 1, height: 48, backgroundColor: '#393080' },
  mockNotice: { color: '#9399A7', fontSize: 11, lineHeight: 17, marginTop: 10 },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 28,
    marginTop: 34,
    marginBottom: 12,
  },
  sectionTitle: { color: colors.navy, fontSize: 22, fontWeight: '900' },
  resultCount: { color: '#9299A8', fontSize: 12 },
  recordCard: {
    borderBottomColor: '#F0F1F4',
    borderBottomWidth: 1,
    backgroundColor: colors.white,
    marginHorizontal: 28,
    paddingBottom: 23,
    paddingTop: 22,
  },
  recordHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  recordDate: { color: colors.muted, fontSize: 14 },
  recordName: { color: colors.navy, fontSize: 19, fontWeight: '900', marginTop: 12 },
  completeBadge: {
    borderRadius: 14,
    backgroundColor: '#DFFFAD',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  completeBadgeText: { color: '#284B00', fontSize: 11, fontWeight: '800' },
  recordChevron: { color: '#CBD1DC', fontSize: 34, lineHeight: 34, marginTop: 2 },
  recordMetrics: { flexDirection: 'row', marginTop: 20 },
  recordMetric: { flex: 1 },
  recordMetricValue: { color: colors.navy, fontSize: 18, fontWeight: '900' },
  recordMetricLabel: { color: colors.muted, fontSize: 12, marginTop: 6 },
  openText: {
    color: '#757D8E',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 17,
    textAlign: 'right',
  },
  emptyCard: {
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E0E3EB',
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
    marginHorizontal: 28,
    padding: 30,
  },
  emptyMark: {
    width: 38,
    height: 38,
    borderWidth: 9,
    borderColor: '#E2F5C4',
    borderRadius: 19,
    backgroundColor: '#A7EF2A',
  },
  emptyTitle: { color: '#252B3B', fontSize: 15, fontWeight: '800', marginTop: 14 },
  emptyDescription: {
    color: '#8C93A1',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 6,
    textAlign: 'center',
  },
  pressed: { opacity: 0.68 },
});
