import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F7F8FA' },
  content: { paddingHorizontal: 20, paddingTop: 24, paddingBottom: 42 },
  screenTitle: { color: '#0A145A', fontSize: 28, fontWeight: '900' },
  screenDescription: { color: '#7A8292', fontSize: 14, marginTop: 7 },
  filterRow: {
    flexDirection: 'row',
    borderRadius: 12,
    backgroundColor: '#EDEFF3',
    padding: 4,
    marginTop: 24,
  },
  filterButton: {
    flex: 1,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
  },
  filterButtonActive: { backgroundColor: '#FFFFFF' },
  filterText: { color: '#878E9D', fontSize: 13, fontWeight: '700' },
  filterTextActive: { color: '#100078' },
  summaryCard: {
    minHeight: 118,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 18,
    backgroundColor: '#100078',
    paddingHorizontal: 17,
    marginTop: 17,
  },
  summaryMetric: { flex: 1, alignItems: 'center' },
  summaryLabel: { color: '#BCC1D8', fontSize: 11 },
  summaryValueRow: { flexDirection: 'row', alignItems: 'flex-end', marginTop: 8 },
  summaryValue: { color: '#C8FF30', fontSize: 22, fontWeight: '900' },
  summaryUnit: { color: '#FFFFFF', fontSize: 11, marginLeft: 3, marginBottom: 3 },
  summaryDivider: { width: 1, height: 48, backgroundColor: '#393080' },
  mockNotice: { color: '#9399A7', fontSize: 11, lineHeight: 17, marginTop: 10 },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 28,
    marginBottom: 12,
  },
  sectionTitle: { color: '#0A145A', fontSize: 19, fontWeight: '900' },
  resultCount: { color: '#9299A8', fontSize: 12 },
  recordCard: {
    borderWidth: 1,
    borderColor: '#E0E3EB',
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
    padding: 17,
    marginBottom: 12,
  },
  recordHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  recordDate: { color: '#9299A8', fontSize: 11 },
  recordName: { color: '#0A145A', fontSize: 16, fontWeight: '800', marginTop: 6 },
  completeBadge: {
    borderRadius: 14,
    backgroundColor: '#DFFFAD',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  completeBadgeText: { color: '#284B00', fontSize: 11, fontWeight: '800' },
  recordMetrics: { flexDirection: 'row', marginTop: 20 },
  recordMetric: { flex: 1 },
  recordMetricValue: { color: '#17204E', fontSize: 17, fontWeight: '900' },
  recordMetricLabel: { color: '#999FAB', fontSize: 11, marginTop: 5 },
  openText: {
    color: '#757D8E',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 17,
    textAlign: 'right',
  },
  emptyCard: {
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E0E3EB',
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
    padding: 30,
  },
  emptyMark: {
    width: 38,
    height: 38,
    borderWidth: 9,
    borderColor: '#E2F5C4',
    borderRadius: 19,
    backgroundColor: '#A7EF2A',
  },
  emptyTitle: { color: '#252B3B', fontSize: 15, fontWeight: '800', marginTop: 14 },
  emptyDescription: {
    color: '#8C93A1',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 6,
    textAlign: 'center',
  },
  pressed: { opacity: 0.68 },
});
