import { StyleSheet } from 'react-native';

import { colors } from '@/styles/tokens';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.navy },
  runningHeader: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
  },
  runningTitle: { color: '#0A145A', fontSize: 22, fontWeight: '900' },
  gpsState: { color: '#218653', fontSize: 12, fontWeight: '700' },
  runningMap: { flex: 1, height: undefined, borderRadius: 0 },
  livePanel: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 12,
  },
  timeValue: { color: '#0A145A', fontSize: 38, fontWeight: '900', textAlign: 'center' },
  timeLabel: { color: '#9299A8', fontSize: 12, marginTop: 4, textAlign: 'center' },
  metricRow: { flexDirection: 'row', marginTop: 22 },
  metricItem: { flex: 1, alignItems: 'center' },
  metricValue: { color: '#17204E', fontSize: 15, fontWeight: '900' },
  metricLabel: { color: '#9299A8', fontSize: 10, marginTop: 5 },
  controlRow: { flexDirection: 'row', gap: 10, marginTop: 22 },
  pauseButton: {
    flex: 1,
    minHeight: 54,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#100078',
    borderRadius: 14,
  },
  pauseButtonText: { color: '#100078', fontSize: 15, fontWeight: '800' },
  finishButton: {
    flex: 1,
    minHeight: 54,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: '#E5484D',
  },
  finishButtonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '800' },
  errorText: { color: '#E5484D', fontSize: 12, lineHeight: 18, marginTop: 12, textAlign: 'center' },
  centerCard: { alignItems: 'center', justifyContent: 'center', flex: 1, padding: 30 },
  pressed: { opacity: 0.68 },
  resultContent: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.navy,
    paddingHorizontal: 28,
    paddingVertical: 40,
  },
  completeMark: {
    width: 74,
    height: 74,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 37,
    backgroundColor: colors.lime,
  },
  completeMarkText: { color: colors.navy, fontSize: 34, fontWeight: '900' },
  resultTitle: { color: colors.white, fontSize: 31, fontWeight: '900', marginTop: 24 },
  resultDescription: { color: '#C9CBE3', fontSize: 15, marginTop: 8 },
  resultCard: {
    alignSelf: 'stretch',
    borderWidth: 0,
    borderRadius: 24,
    backgroundColor: colors.white,
    padding: 24,
    marginTop: 28,
  },
  resultMetric: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
  },
  resultMetricLabel: { color: colors.muted, fontSize: 14 },
  resultMetricValue: { color: colors.navy, fontSize: 20, fontWeight: '900' },
  sessionText: { color: '#C9CBE3', fontSize: 12, marginTop: 14 },
  resultPrimaryButton: {
    alignSelf: 'stretch',
    minHeight: 56,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: colors.lime,
    marginTop: 26,
  },
  resultPrimaryText: { color: colors.navy, fontSize: 17, fontWeight: '900' },
  resultSecondaryButton: {
    alignSelf: 'stretch',
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#BFC3E5',
    borderRadius: 20,
    marginTop: 10,
  },
  resultSecondaryText: { color: colors.white, fontSize: 15, fontWeight: '800' },
});
