import { StyleSheet } from 'react-native';

import { colors } from '@/styles/tokens';

/** 코스 설정 2~4단계가 함께 사용하는 기본 스타일입니다. */
export const courseFlowStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    minHeight: 84,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomColor: '#F3F4F6',
    borderBottomWidth: 1,
    paddingHorizontal: 28,
  },
  backButton: {
    width: 36,
    color: colors.navy,
    fontSize: 40,
    lineHeight: 42,
  },
  screenTitle: {
    flex: 1,
    color: colors.navy,
    fontSize: 22,
    fontWeight: '900',
    marginLeft: 8,
  },
  stepBadge: {
    minWidth: 58,
    alignItems: 'center',
    borderRadius: 18,
    backgroundColor: colors.pageIndigo,
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  stepText: {
    color: colors.navy,
    fontSize: 14,
    fontWeight: '800',
  },
  content: {
    paddingHorizontal: 28,
    paddingTop: 28,
    paddingBottom: 52,
  },
  introTitle: {
    color: colors.navy,
    fontSize: 27,
    fontWeight: '900',
    lineHeight: 36,
  },
  introText: {
    color: colors.muted,
    fontSize: 16,
    lineHeight: 24,
    marginTop: 9,
  },
  section: {
    marginTop: 30,
  },
  sectionTitle: {
    color: colors.navy,
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 12,
  },
  sectionHelp: {
    color: '#9399A7',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 9,
  },
  distanceInputRow: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.inactive,
    borderRadius: 14,
    backgroundColor: colors.cardBg,
    paddingHorizontal: 16,
  },
  distanceInput: {
    flex: 1,
    color: colors.navy,
    fontSize: 20,
    fontWeight: '800',
    paddingVertical: 10,
  },
  distanceUnit: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: '700',
  },
  textArea: {
    minHeight: 126,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 18,
    backgroundColor: colors.white,
    color: colors.navy,
    fontSize: 15,
    lineHeight: 22,
    paddingHorizontal: 16,
    paddingTop: 15,
    paddingBottom: 32,
    textAlignVertical: 'top',
  },
  characterCount: {
    alignSelf: 'flex-end',
    color: '#A0A6B2',
    fontSize: 11,
    marginTop: -24,
    marginRight: 13,
  },
  optionRow: {
    flexDirection: 'row',
    gap: 9,
  },
  optionButton: {
    flex: 1,
    minHeight: 100,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0,
    borderRadius: 18,
    backgroundColor: colors.inactive,
    paddingHorizontal: 8,
  },
  optionButtonActive: {
    backgroundColor: colors.navy,
  },
  optionText: {
    color: colors.textBody,
    fontSize: 16,
    fontWeight: '800',
  },
  optionTextActive: {
    color: colors.lime,
  },
  optionDescription: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 7,
  },
  optionDescriptionActive: {
    color: '#D9FAA0',
  },
  facilityButton: {
    flex: 1,
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 0,
    borderRadius: 14,
    backgroundColor: colors.inactive,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  facilityButtonActive: {
    backgroundColor: colors.navy,
  },
  checkCircle: {
    width: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#BFC6D2',
    borderRadius: 9,
    marginRight: 8,
  },
  checkCircleActive: {
    borderColor: colors.lime,
    backgroundColor: colors.lime,
  },
  checkText: {
    color: colors.navy,
    fontSize: 13,
    fontWeight: '900',
  },
  importanceRow: {
    flexDirection: 'row',
    gap: 5,
  },
  starButton: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 2,
  },
  importanceButton: {
    flex: 1,
    minHeight: 45,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E0E3EA',
    borderRadius: 10,
    backgroundColor: '#F8F9FC',
  },
  importanceButtonActive: {
    borderColor: '#100078',
    backgroundColor: '#100078',
  },
  importanceText: {
    color: '#7B8292',
    fontSize: 14,
    fontWeight: '700',
  },
  importanceTextActive: {
    color: '#C8FF30',
  },
  importanceGuide: {
    marginTop: 8,
  },
  importanceGuideText: {
    color: colors.muted,
    fontSize: 13,
  },
  primaryButton: {
    minHeight: 58,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: colors.navy,
    paddingHorizontal: 18,
    marginTop: 36,
  },
  primaryButtonText: {
    color: colors.lime,
    fontSize: 17,
    fontWeight: '900',
  },
  secondaryButton: {
    flex: 1,
    minHeight: 56,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#D9DCE5',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
  },
  secondaryButtonText: {
    color: '#100078',
    fontSize: 15,
    fontWeight: '800',
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 34,
  },
  buttonRowPrimary: {
    flex: 2,
    marginTop: 0,
  },
  completeBadge: {
    alignSelf: 'flex-start',
    borderRadius: 18,
    backgroundColor: '#EEFFD2',
    paddingHorizontal: 13,
    paddingVertical: 8,
    marginTop: 24,
  },
  completeBadgeText: {
    color: '#405B00',
    fontSize: 12,
    fontWeight: '800',
  },
  summaryCard: {
    borderWidth: 1,
    borderColor: '#E1E4ED',
    borderRadius: 17,
    backgroundColor: '#F8F9FD',
    padding: 18,
    marginTop: 22,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 10,
  },
  summaryLabel: {
    width: 88,
    color: '#8A91A0',
    fontSize: 13,
    fontWeight: '600',
  },
  summaryValue: {
    flex: 1,
    color: '#202747',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
  },
  noticeText: {
    color: '#9299A8',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 12,
  },
  importanceSection: {
    marginTop: 28,
  },
  importanceItem: {
    marginBottom: 20,
  },
  importanceLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  importanceLabel: {
    color: '#252B3B',
    fontSize: 14,
    fontWeight: '700',
  },
  importanceValue: {
    color: '#100078',
    fontSize: 12,
    fontWeight: '800',
  },
  compareHelp: {
    color: '#7D8495',
    fontSize: 13,
    lineHeight: 20,
    marginTop: 8,
    marginBottom: 20,
  },
  compareStartPoint: {
    color: colors.muted,
    fontSize: 14,
    marginBottom: 14,
  },
  courseCard: {
    borderWidth: 2,
    borderColor: colors.cardBorder,
    borderRadius: 24,
    backgroundColor: colors.white,
    padding: 22,
    marginBottom: 13,
  },
  courseCardActive: {
    borderWidth: 2,
    borderColor: colors.navy,
    backgroundColor: colors.white,
    padding: 22,
  },
  courseHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  courseLabel: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    backgroundColor: '#100078',
  },
  courseRadio: {
    alignItems: 'center',
    borderColor: '#CBD1DC',
    borderRadius: 16,
    borderWidth: 2,
    height: 32,
    justifyContent: 'center',
    marginTop: 4,
    width: 32,
  },
  courseRadioActive: {
    borderColor: colors.navy,
  },
  courseRadioDot: {
    backgroundColor: colors.navy,
    borderRadius: 8,
    height: 16,
    width: 16,
  },
  courseLabelText: {
    color: '#C8FF30',
    fontSize: 16,
    fontWeight: '900',
  },
  courseCopy: {
    flex: 1,
    marginLeft: 12,
  },
  courseName: {
    color: colors.navy,
    fontSize: 23,
    fontWeight: '900',
  },
  courseSummary: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 18,
    marginTop: 5,
  },
  scoreText: {
    color: colors.navy,
    fontSize: 16,
    fontWeight: '900',
    marginTop: 4,
    textAlign: 'right',
  },
  courseNameRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  recommendBadge: {
    backgroundColor: colors.lime,
    borderRadius: 12,
    color: colors.navy,
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  scoreBlock: {
    alignItems: 'flex-end',
    minWidth: 88,
  },
  scoreLabel: {
    color: colors.muted,
    fontSize: 11,
  },
  scoreLine: {
    backgroundColor: colors.inactive,
    borderRadius: 4,
    height: 8,
    marginTop: 7,
    overflow: 'hidden',
    width: 74,
  },
  scoreFill: {
    backgroundColor: colors.lime,
    borderRadius: 4,
    height: '100%',
  },
  metricRow: {
    flexDirection: 'row',
    marginTop: 18,
  },
  metricItem: {
    flex: 1,
  },
  metricLabel: {
    color: '#9AA0AD',
    fontSize: 11,
  },
  metricValue: {
    color: '#202747',
    fontSize: 15,
    fontWeight: '800',
    marginTop: 5,
  },
  detailsDivider: {
    height: 1,
    backgroundColor: '#E6E8EF',
    marginVertical: 18,
  },
  detailGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 22,
  },
  detailItem: {
    width: '50%',
  },
  metricTile: {
    backgroundColor: '#F9FAFB',
    borderRadius: 18,
    padding: 14,
    width: '47%',
  },
  detailLabel: {
    color: '#969CAA',
    fontSize: 11,
  },
  detailValue: {
    color: '#252B3B',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 4,
  },
  reasonTitle: {
    color: colors.navy,
    fontSize: 14,
    fontWeight: '800',
    marginTop: 0,
  },
  reasonText: {
    color: colors.textSub,
    fontSize: 12,
    lineHeight: 19,
    marginTop: 7,
  },
  reasonBox: {
    backgroundColor: colors.pageIndigo,
    borderRadius: 18,
    marginTop: 20,
    padding: 16,
  },
  selectedHint: {
    color: '#100078',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 14,
    textAlign: 'center',
  },
  pressed: {
    opacity: 0.68,
  },
});
