import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F7F8FA' },
  header: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
  },
  backButton: { width: 36, color: '#0A145A', fontSize: 38, lineHeight: 40 },
  screenTitle: { flex: 1, color: '#0A145A', fontSize: 22, fontWeight: '900' },
  bookmarkButton: { color: '#100078', fontSize: 28 },
  loader: { marginTop: 60 },
  centerCard: { alignItems: 'center', padding: 30, marginTop: 40 },
  content: { padding: 20, paddingBottom: 44 },
  map: { height: 330 },
  courseName: { color: '#0A145A', fontSize: 24, fontWeight: '900', marginTop: 22 },
  metricRow: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#E0E3EB',
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    paddingVertical: 18,
    marginTop: 16,
  },
  metricItem: { flex: 1, alignItems: 'center' },
  metricValue: { color: '#17204E', fontSize: 17, fontWeight: '900' },
  metricLabel: { color: '#9299A8', fontSize: 11, marginTop: 6 },
  noticeText: { color: '#7D8495', fontSize: 13, lineHeight: 20, marginTop: 14 },
  errorText: { color: '#E5484D', fontSize: 13, lineHeight: 20, marginTop: 14, textAlign: 'center' },
  retryText: { color: '#100078', fontSize: 14, fontWeight: '800', marginTop: 16 },
  startButton: {
    minHeight: 58,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: '#100078',
    marginTop: 26,
  },
  startButtonText: { color: '#C8FF30', fontSize: 16, fontWeight: '900' },
  pressed: { opacity: 0.68 },
});
