import { StyleSheet } from 'react-native';

/** 코스 설정 2~4단계가 함께 사용하는 기본 스타일입니다. */
export const courseFlowStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  backButton: {
    width: 36,
    color: '#0A145A',
    fontSize: 38,
    lineHeight: 40,
  },
  screenTitle: {
    flex: 1,
    color: '#0A145A',
    fontSize: 23,
    fontWeight: '800',
    marginLeft: 6,
  },
  stepBadge: {
    minWidth: 58,
    alignItems: 'center',
    borderRadius: 18,
    backgroundColor: '#F0F2FF',
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  stepText: {
    color: '#100078',
    fontSize: 14,
    fontWeight: '800',
  },
  content: {
    paddingHorizontal: 24,
    paddingTop: 22,
    paddingBottom: 48,
  },
  introTitle: {
    color: '#0A145A',
    fontSize: 27,
    fontWeight: '900',
    lineHeight: 36,
  },
  introText: {
    color: '#7D8495',
    fontSize: 14,
    lineHeight: 21,
    marginTop: 9,
  },
  section: {
    marginTop: 30,
  },
  sectionTitle: {
    color: '#151C4F',
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 12,
  },
  sectionHelp: {
    color: '#9399A7',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 9,
  },
  textArea: {
    minHeight: 126,
    borderWidth: 1,
    borderColor: '#E0E3EB',
    borderRadius: 16,
    backgroundColor: '#F8F9FC',
    color: '#252B3B',
    fontSize: 15,
    lineHeight: 22,
    paddingHorizontal: 16,
    paddingTop: 15,
    paddingBottom: 32,
    textAlignVertical: 'top',
  },
  characterCount: {
    alignSelf: 'flex-end',
    color: '#A0A6B2',
    fontSize: 11,
    marginTop: -24,
    marginRight: 13,
  },
  optionRow: {
    flexDirection: 'row',
    gap: 9,
  },
  optionButton: {
    flex: 1,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#DEE1E9',
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 8,
  },
  optionButtonActive: {
    borderColor: '#100078',
    backgroundColor: '#F1F0FF',
  },
  optionText: {
    color: '#757D8E',
    fontSize: 14,
    fontWeight: '700',
  },
  optionTextActive: {
    color: '#100078',
  },
  facilityButton: {
    flex: 1,
    minHeight: 66,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#DEE1E9',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 15,
  },
  facilityButtonActive: {
    borderColor: '#A7EF2A',
    backgroundColor: '#F3FFDF',
  },
  checkCircle: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#CBD0DB',
    borderRadius: 11,
    marginRight: 10,
  },
  checkCircleActive: {
    borderColor: '#100078',
    backgroundColor: '#100078',
  },
  checkText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
  importanceRow: {
    flexDirection: 'row',
    gap: 8,
  },
  importanceButton: {
    flex: 1,
    minHeight: 45,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E0E3EA',
    borderRadius: 10,
    backgroundColor: '#F8F9FC',
  },
  importanceButtonActive: {
    borderColor: '#100078',
    backgroundColor: '#100078',
  },
  importanceText: {
    color: '#7B8292',
    fontSize: 14,
    fontWeight: '700',
  },
  importanceTextActive: {
    color: '#C8FF30',
  },
  importanceGuide: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  importanceGuideText: {
    color: '#A0A6B2',
    fontSize: 11,
  },
  primaryButton: {
    minHeight: 58,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: '#100078',
    paddingHorizontal: 18,
    marginTop: 36,
  },
  primaryButtonText: {
    color: '#C8FF30',
    fontSize: 16,
    fontWeight: '900',
  },
  secondaryButton: {
    flex: 1,
    minHeight: 56,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#D9DCE5',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
  },
  secondaryButtonText: {
    color: '#100078',
    fontSize: 15,
    fontWeight: '800',
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 34,
  },
  buttonRowPrimary: {
    flex: 2,
    marginTop: 0,
  },
  completeBadge: {
    alignSelf: 'flex-start',
    borderRadius: 18,
    backgroundColor: '#EEFFD2',
    paddingHorizontal: 13,
    paddingVertical: 8,
    marginTop: 24,
  },
  completeBadgeText: {
    color: '#405B00',
    fontSize: 12,
    fontWeight: '800',
  },
  summaryCard: {
    borderWidth: 1,
    borderColor: '#E1E4ED',
    borderRadius: 17,
    backgroundColor: '#F8F9FD',
    padding: 18,
    marginTop: 22,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 10,
  },
  summaryLabel: {
    width: 88,
    color: '#8A91A0',
    fontSize: 13,
    fontWeight: '600',
  },
  summaryValue: {
    flex: 1,
    color: '#202747',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
  },
  noticeText: {
    color: '#9299A8',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 12,
  },
  importanceSection: {
    marginTop: 28,
  },
  importanceItem: {
    marginBottom: 20,
  },
  importanceLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  importanceLabel: {
    color: '#252B3B',
    fontSize: 14,
    fontWeight: '700',
  },
  importanceValue: {
    color: '#100078',
    fontSize: 12,
    fontWeight: '800',
  },
  compareHelp: {
    color: '#7D8495',
    fontSize: 13,
    lineHeight: 20,
    marginTop: 8,
    marginBottom: 20,
  },
  courseCard: {
    borderWidth: 1,
    borderColor: '#E0E3EB',
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    padding: 18,
    marginBottom: 13,
  },
  courseCardActive: {
    borderWidth: 2,
    borderColor: '#100078',
    backgroundColor: '#F9F9FF',
    padding: 17,
  },
  courseHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  courseLabel: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    backgroundColor: '#100078',
  },
  courseLabelText: {
    color: '#C8FF30',
    fontSize: 16,
    fontWeight: '900',
  },
  courseCopy: {
    flex: 1,
    marginLeft: 12,
  },
  courseName: {
    color: '#0A145A',
    fontSize: 17,
    fontWeight: '900',
  },
  courseSummary: {
    color: '#848B9A',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 5,
  },
  scoreText: {
    color: '#100078',
    fontSize: 17,
    fontWeight: '900',
    marginLeft: 10,
  },
  metricRow: {
    flexDirection: 'row',
    marginTop: 18,
  },
  metricItem: {
    flex: 1,
  },
  metricLabel: {
    color: '#9AA0AD',
    fontSize: 11,
  },
  metricValue: {
    color: '#202747',
    fontSize: 15,
    fontWeight: '800',
    marginTop: 5,
  },
  detailsDivider: {
    height: 1,
    backgroundColor: '#E6E8EF',
    marginVertical: 18,
  },
  detailGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: 16,
  },
  detailItem: {
    width: '50%',
  },
  detailLabel: {
    color: '#969CAA',
    fontSize: 11,
  },
  detailValue: {
    color: '#252B3B',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 4,
  },
  reasonTitle: {
    color: '#0A145A',
    fontSize: 14,
    fontWeight: '800',
    marginTop: 20,
  },
  reasonText: {
    color: '#626A7B',
    fontSize: 12,
    lineHeight: 19,
    marginTop: 7,
  },
  selectedHint: {
    color: '#100078',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 14,
    textAlign: 'center',
  },
  pressed: {
    opacity: 0.68,
  },
});
