import { StyleSheet } from 'react-native';

import { colors } from '@/styles/tokens';

export const styles = StyleSheet.create({
  safeArea: { backgroundColor: '#FFFFFF', flex: 1 },
  content: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingBottom: 24,
    paddingHorizontal: 40,
    paddingTop: 24,
  },
  brandRow: { alignItems: 'center', flexDirection: 'row' },
  brandMark: {
    alignItems: 'center',
    backgroundColor: colors.navy,
    borderRadius: 10,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  brandMarkText: {
    color: colors.lime,
    fontSize: 13,
    fontStyle: 'italic',
    fontWeight: '900',
  },
  brandName: {
    color: colors.navy,
    fontFamily: 'sans-serif-condensed',
    fontSize: 29,
    fontStyle: 'italic',
    fontWeight: '900',
    letterSpacing: -1.3,
    marginLeft: 10,
  },
  subtitle: {
    color: '#94A0B3',
    fontSize: 14,
    marginLeft: 46,
    marginTop: 10,
  },
  form: { marginTop: 19 },
  fieldGroup: { marginBottom: 17 },
  label: {
    color: '#8E99AA',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 5,
  },
  input: {
    borderBottomColor: '#DCE1E8',
    borderBottomWidth: 1,
    color: '#182230',
    fontSize: 14,
    minHeight: 38,
    paddingHorizontal: 0,
    paddingVertical: 4,
  },
  passwordRow: {
    alignItems: 'center',
    borderBottomColor: '#DCE1E8',
    borderBottomWidth: 1,
    flexDirection: 'row',
    minHeight: 38,
  },
  passwordInput: {
    color: '#182230',
    flex: 1,
    fontSize: 14,
    paddingHorizontal: 0,
    paddingVertical: 4,
  },
  visibilityButton: {
    alignItems: 'center',
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  eyeOutline: {
    borderColor: '#9FAABC',
    borderRadius: 9,
    borderWidth: 1.5,
    height: 14,
    justifyContent: 'center',
    transform: [{ scaleX: 1.45 }],
    width: 14,
  },
  eyeOutlineActive: { borderColor: colors.navy },
  eyePupil: {
    alignSelf: 'center',
    backgroundColor: '#9FAABC',
    borderRadius: 3,
    height: 5,
    width: 5,
  },
  eyePupilActive: { backgroundColor: colors.navy },
  inputError: { borderBottomColor: '#F04438' },
  errorText: { color: '#F04438', fontSize: 13, marginTop: 8 },
  serverErrorText: {
    color: '#F04438',
    fontSize: 13,
    marginTop: 12,
    textAlign: 'center',
  },
  loginButton: {
    alignItems: 'center',
    backgroundColor: colors.navy,
    borderRadius: 10,
    justifyContent: 'center',
    minHeight: 54,
    marginTop: 8,
  },
  loginButtonText: { color: colors.lime, fontSize: 16, fontWeight: '700' },
  links: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 30,
  },
  linkText: { color: '#748199', fontSize: 12, fontWeight: '600' },
  primaryLinkText: { color: colors.navy, fontWeight: '900' },
  linkDivider: { color: '#D6DAE2', fontSize: 12, marginHorizontal: 10 },
  previewButton: { alignSelf: 'center', marginTop: 28, padding: 8 },
  previewButtonText: { color: '#98A2B3', fontSize: 11 },
  disabledButton: { opacity: 0.55 },
  pressed: { opacity: 0.72 },
});
