import { StyleSheet } from 'react-native';

import { colors } from '@/styles/tokens';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  content: {
    flexGrow: 1,
    paddingBottom: 24,
  },
  header: {
    alignItems: 'center',
    borderBottomColor: '#EEF0F4',
    borderBottomWidth: 1,
    flexDirection: 'row',
    minHeight: 72,
    paddingHorizontal: 34,
  },
  backButton: {
    color: colors.navy,
    fontSize: 28,
    lineHeight: 30,
    marginRight: 12,
  },
  title: {
    color: colors.navy,
    flex: 1,
    fontSize: 22,
    fontWeight: '900',
  },
  stepIndicator: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  stepIndicatorActive: {
    backgroundColor: colors.navy,
    borderRadius: 4,
    height: 5,
    width: 22,
  },
  stepIndicatorInactive: {
    backgroundColor: '#E1E5EB',
    borderRadius: 4,
    height: 5,
    width: 22,
  },
  form: {
    paddingHorizontal: 34,
    paddingTop: 22,
  },
  description: {
    color: '#687791',
    fontSize: 14,
    marginBottom: 19,
  },
  label: {
    color: '#8E99AA',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 5,
    marginTop: 17,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderBottomColor: '#DCE1E8',
    borderBottomWidth: 1,
    color: '#182230',
    fontSize: 14,
    minHeight: 36,
    paddingHorizontal: 0,
  },
  row: {
    alignItems: 'flex-end',
    flexDirection: 'row',
  },
  rowInput: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderBottomColor: '#DCE1E8',
    borderBottomWidth: 1,
    color: '#182230',
    fontSize: 14,
    minHeight: 36,
    paddingHorizontal: 0,
  },
  passwordRow: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderBottomColor: '#DCE1E8',
    borderBottomWidth: 1,
    flexDirection: 'row',
    minHeight: 36,
  },
  passwordInput: {
    color: '#182230',
    flex: 1,
    fontSize: 14,
    paddingHorizontal: 0,
  },
  visibilityButton: {
    alignItems: 'center',
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  eyeOutline: {
    borderColor: '#9FAABC',
    borderRadius: 8,
    borderWidth: 1.5,
    height: 14,
    justifyContent: 'center',
    transform: [{ scaleX: 1.45 }],
    width: 14,
  },
  eyeOutlineActive: {
    borderColor: colors.navy,
  },
  eyePupil: {
    alignSelf: 'center',
    backgroundColor: '#9FAABC',
    borderRadius: 3,
    height: 5,
    width: 5,
  },
  eyePupilActive: {
    backgroundColor: colors.navy,
  },
  smallButton: {
    alignItems: 'center',
    backgroundColor: colors.navy,
    borderRadius: 8,
    justifyContent: 'center',
    marginLeft: 8,
    minHeight: 29,
    minWidth: 66,
    paddingHorizontal: 8,
  },
  smallButtonText: {
    color: colors.lime,
    fontSize: 13,
    fontWeight: '900',
  },
  inputError: {
    borderBottomColor: '#F04438',
  },
  errorText: {
    color: '#F04438',
    fontSize: 13,
    marginTop: 7,
  },
  successText: {
    color: '#299764',
    fontSize: 13,
    marginTop: 7,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: colors.navy,
    borderRadius: 10,
    justifyContent: 'center',
    marginTop: 28,
    minHeight: 54,
  },
  primaryButtonText: {
    color: colors.lime,
    fontSize: 16,
    fontWeight: '700',
  },
  infoBox: {
    borderRadius: 14,
    marginTop: 28,
    padding: 16,
    backgroundColor: '#F4F6FA',
  },
  infoTitle: {
    color: colors.navy,
    fontWeight: '700',
    marginBottom: 6,
  },
  infoText: {
    color: '#555B6B',
    fontSize: 13,
    lineHeight: 19,
  },
  footerRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 32,
  },
  secondaryButton: {
    flex: 1,
    alignItems: 'center',
    borderColor: colors.navy,
    borderRadius: 20,
    borderWidth: 2,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    minHeight: 58,
  },
  secondaryButtonText: {
    color: colors.navy,
    fontSize: 16,
    fontWeight: '800',
  },
  footerPrimaryButton: {
    flex: 1.5,
    alignItems: 'center',
    backgroundColor: colors.navy,
    borderRadius: 20,
    justifyContent: 'center',
    minHeight: 58,
  },
});
