import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  content: {
    flexGrow: 1,
    padding: 24,
    paddingBottom: 40,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginBottom: 28,
  },
  backButton: {
    color: '#0A145A',
    fontSize: 38,
    lineHeight: 38,
  },
  title: {
    color: '#0A145A',
    fontSize: 28,
    fontWeight: '700',
  },
  form: {
    gap: 10,
  },
  description: {
    color: '#666666',
    fontSize: 15,
    marginBottom: 18,
  },
  label: {
    color: '#555B6B',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 6,
  },
  input: {
    minHeight: 50,
    borderWidth: 1,
    borderColor: '#D9DCE3',
    borderRadius: 8,
    paddingHorizontal: 14,
    color: '#111111',
    backgroundColor: '#FFFFFF',
  },
  row: {
    flexDirection: 'row',
    gap: 8,
  },
  rowInput: {
    flex: 1,
    minHeight: 50,
    borderWidth: 1,
    borderColor: '#D9DCE3',
    borderRadius: 8,
    paddingHorizontal: 14,
    color: '#111111',
    backgroundColor: '#FFFFFF',
  },
  passwordRow: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#D9DCE3',
    borderRadius: 8,
    paddingHorizontal: 14,
    backgroundColor: '#FFFFFF',
  },
  passwordInput: {
    flex: 1,
    color: '#111111',
  },
  visibilityButton: {
    color: '#0A145A',
    fontWeight: '600',
    padding: 6,
  },
  smallButton: {
    minWidth: 82,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#0A145A',
    borderRadius: 8,
    paddingHorizontal: 12,
    backgroundColor: '#FFFFFF',
  },
  smallButtonText: {
    color: '#0A145A',
    fontSize: 13,
    fontWeight: '700',
  },
  inputError: {
    borderColor: '#FF3B30',
  },
  errorText: {
    color: '#FF3B30',
    fontSize: 13,
  },
  successText: {
    color: '#169B62',
    fontSize: 13,
  },
  primaryButton: {
    minHeight: 54,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    marginTop: 22,
    backgroundColor: '#100078',
  },
  primaryButtonText: {
    color: '#C8FF30',
    fontSize: 16,
    fontWeight: '700',
  },
  infoBox: {
    borderRadius: 10,
    marginTop: 14,
    padding: 16,
    backgroundColor: '#F4F6FA',
  },
  infoTitle: {
    color: '#0A145A',
    fontWeight: '700',
    marginBottom: 6,
  },
  infoText: {
    color: '#555B6B',
    fontSize: 13,
    lineHeight: 19,
  },
  footerRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 24,
  },
  secondaryButton: {
    flex: 1,
    minHeight: 54,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#100078',
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
  },
  secondaryButtonText: {
    color: '#100078',
    fontSize: 16,
    fontWeight: '700',
  },
  footerPrimaryButton: {
    flex: 1.5,
    minHeight: 54,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: '#100078',
  },
});
