import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F7F8FA' },
  header: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
  },
  backButton: { width: 36, color: '#0A145A', fontSize: 38, lineHeight: 40 },
  screenTitle: { color: '#0A145A', fontSize: 22, fontWeight: '900', marginLeft: 6 },
  tabRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#E4E6EC',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
    paddingVertical: 15,
  },
  tabButtonActive: { borderBottomColor: '#100078' },
  tabText: { color: '#9299A8', fontSize: 14, fontWeight: '700' },
  tabTextActive: { color: '#100078' },
  content: { paddingHorizontal: 20, paddingTop: 17, paddingBottom: 46 },
  mockNotice: { color: '#9399A7', fontSize: 11, lineHeight: 17, marginBottom: 14 },
  card: {
    borderWidth: 1,
    borderColor: '#E0E3EB',
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
    padding: 17,
    marginBottom: 12,
  },
  cardHeader: { flexDirection: 'row', alignItems: 'flex-start' },
  courseMark: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: '#100078',
  },
  courseMarkText: { color: '#C8FF30', fontSize: 17, fontWeight: '900' },
  placeMark: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: '#E8F8C9',
  },
  placeMarkText: { color: '#100078', fontSize: 16, fontWeight: '900' },
  cardCopy: { flex: 1, marginLeft: 12 },
  cardTitle: { color: '#0A145A', fontSize: 16, fontWeight: '900' },
  cardSubtitle: { color: '#8B92A0', fontSize: 12, lineHeight: 18, marginTop: 5 },
  categoryText: { color: '#596275', fontSize: 11, fontWeight: '700', marginTop: 5 },
  bookmarkButton: { color: '#100078', fontSize: 22, marginLeft: 9 },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 16 },
  tag: {
    borderRadius: 12,
    backgroundColor: '#F0F1FA',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  tagText: { color: '#3B4271', fontSize: 11, fontWeight: '700' },
  outlineButton: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#100078',
    borderRadius: 11,
    marginTop: 17,
  },
  outlineButtonText: { color: '#100078', fontSize: 13, fontWeight: '800' },
  primaryButton: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    backgroundColor: '#100078',
    marginTop: 17,
  },
  primaryButtonText: { color: '#C8FF30', fontSize: 13, fontWeight: '800' },
  emptyCard: {
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E0E3EB',
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 24,
    paddingVertical: 42,
  },
  emptyStar: { color: '#A7EF2A', fontSize: 42 },
  emptyTitle: { color: '#252B3B', fontSize: 15, fontWeight: '800', marginTop: 12 },
  emptyDescription: {
    color: '#8C93A1',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 7,
    textAlign: 'center',
  },
  pressed: { opacity: 0.68 },
});
